### ISSUE TITLE
OSX compatibility

### ISSUE THREAD

**Issue by IronicBadger** [materye/poormanswiki#4]
On MacOS this fails due to differences in the available `find` program.

    $ ./wikis/wiki-update.sh
    find: -printf: unknown primary or operator

The -printf option is not in POSIX find. It is a feature of GNU find, e.g., on Linux.

As per this [stackexchange](https://unix.stackexchange.com/questions/272491/bash-error-find-printf-unknown-primary-or-operator).

**Comment by materye** [comment]
Should be fixed with commit  **68b84e3**
